-- =============================================================================
-- Transgar - 30: Personas (empleados) desde hoja 'No. EMPLEADO'
-- Prefijo del No.: 1=OTRO(admin) 2=MECANICO(taller) 3/4=CONDUCTOR(motoristas)
-- Requiere 00. Idempotente por (id_empresa, documento).
-- =============================================================================
SET QUOTED_IDENTIFIER ON; SET ANSI_NULLS ON; SET NOCOUNT ON;
DECLARE @IdEmpresa INT = (SELECT id_empresa FROM dbo.empresas WHERE codigo='TRANSGAR');
IF @IdEmpresa IS NULL BEGIN RAISERROR('Empresa TRANSGAR no existe. Ejecute 00 primero.',16,1); RETURN; END
DECLARE @Ahora DATETIME2(3)=SYSUTCDATETIME();
IF OBJECT_ID('tempdb..#per') IS NOT NULL DROP TABLE #per;
CREATE TABLE #per (documento varchar(30), nombres nvarchar(100), apellidos nvarchar(100), cargo varchar(30));
INSERT INTO #per (documento,nombres,apellidos,cargo) VALUES
(N'10001',N'FREDY WILSON',N'MARTINEZ SANCHEZ','OTRO'),
(N'10002',N'EDWIN',N'JOEL MARTINEZ','OTRO'),
(N'10003',N'JORGE',N'ALBERTO PERDOMO','OTRO'),
(N'10004',N'SERGIO JACOBO',N'HANDALL FABREGAS','OTRO'),
(N'10005',N'OSMAR',N'ADELMO DIAZ','OTRO'),
(N'10006',N'ESMELIN',N'RIVERA PEREZ','OTRO'),
(N'10007',N'JAVIER',N'OMAR QUIÑONEZ','OTRO'),
(N'10008',N'OSCAR',N'CRUZ SANCHEZ','OTRO'),
(N'10009',N'CARLOS',N'ROBERTO BARAONA','OTRO'),
(N'10010',N'NIXON',N'LOPEZ','OTRO'),
(N'20001',N'ANDY',N'DANIEL ORTEGA','MECANICO'),
(N'20002',N'RUBEN',N'ARMANDO GONZALEZ','MECANICO'),
(N'20004',N'MARCOS',N'FUNEZ','MECANICO'),
(N'20006',N'DANILO',N'BUESO','MECANICO'),
(N'20007',N'SANTIAGO',N'BAUTISTTA','MECANICO'),
(N'20008',N'BENEDICTO',N'AMAYA','MECANICO'),
(N'20009',N'SANTOS',N'HERRERA','MECANICO'),
(N'20010',N'ANGEL',N'CRUZ','MECANICO'),
(N'20011',N'SANTOS',N'FLORES','MECANICO'),
(N'20012',N'JEFRI',N'RIVERA HERNANDEZ','MECANICO'),
(N'30001',N'MARIO',N'ENRIQUE LANZA','CONDUCTOR'),
(N'30002',N'OSCAR',N'RIGOBERTO NAVARRO','CONDUCTOR'),
(N'30003',N'MIGUEL',N'ANTONIO MARTINEZ','CONDUCTOR'),
(N'30004',N'REYNALDO',N'CABRERA','CONDUCTOR'),
(N'30005',N'JOSE',N'VICTOR GOMEZ','CONDUCTOR'),
(N'30006',N'RONY',N'PINEDA BONILLA','CONDUCTOR'),
(N'30007',N'ROMEO',N'ISMAEL RIVERA','CONDUCTOR'),
(N'30008',N'JAVIER',N'ALEXIS SARAVIA','CONDUCTOR'),
(N'30009',N'OMAR',N'SARAVIA AMAYA','CONDUCTOR'),
(N'30010',N'ROQUE',N'VASQUEZ ANDINO','CONDUCTOR'),
(N'30011',N'LUIS RAMIRO',N'REYES PALMA','CONDUCTOR'),
(N'30012',N'CARLOS',N'ROSALES','CONDUCTOR'),
(N'30013',N'FELIPE',N'MEMBREÑO SAGATUME','CONDUCTOR'),
(N'30014',N'NELSON',N'OMAR CASTILLO','CONDUCTOR'),
(N'30015',N'BENIGNO',N'ARGUETA ROBLES','CONDUCTOR'),
(N'30016',N'MARVIN',N'MANUEL MEJIA','CONDUCTOR'),
(N'30017',N'JULIO',N'CESAR PEREA','CONDUCTOR'),
(N'30018',N'PEDRO',N'ANTONIO BUSTILLO','CONDUCTOR'),
(N'30019',N'JOEL',N'ALEXANDER CASTILLO','CONDUCTOR'),
(N'30020',N'JOSIAS',N'ALVARENGA','CONDUCTOR'),
(N'30021',N'OSCAR',N'IVAN ORTEZ','CONDUCTOR'),
(N'30022',N'FRANKLIN',N'RAMON CRUZ','CONDUCTOR'),
(N'30023',N'MELVIN',N'CRUZ','CONDUCTOR'),
(N'30024',N'CARLOS',N'ALBERTO MELENDEZ','CONDUCTOR'),
(N'30025',N'RENE',N'VICENTE SUAZO','CONDUCTOR'),
(N'30026',N'MAYNOR',N'JONATHAN LOPEZ','CONDUCTOR'),
(N'30027',N'DENIS',N'RAMON PAZ','CONDUCTOR'),
(N'30028',N'JUAN',N'CARLOS GALLO','CONDUCTOR'),
(N'30029',N'DENIS',N'GERARDO CARIAS','CONDUCTOR'),
(N'30030',N'JUAN',N'DURON','CONDUCTOR'),
(N'30031',N'CARLOS',N'RIVERA','CONDUCTOR'),
(N'30032',N'LUIGUI',N'GONZALEZ','CONDUCTOR'),
(N'30033',N'OMAR',N'ARGUETA','CONDUCTOR'),
(N'30034',N'OSCAR',N'CRUZ HIJO','CONDUCTOR'),
(N'30035',N'CARLOS',N'MENDOZA','CONDUCTOR'),
(N'30036',N'MARVIN',N'LOPEZ','CONDUCTOR'),
(N'30037',N'MELVIN',N'ELVIR','CONDUCTOR'),
(N'30038',N'ALBERT',N'SARAVIA','CONDUCTOR'),
(N'30039',N'JHONY',N'GUEVARA','CONDUCTOR'),
(N'30040',N'HENRY',N'RODRIGUEZ','CONDUCTOR'),
(N'30041',N'JOSE',N'BUSTILLO','CONDUCTOR'),
(N'30042',N'FERDY',N'ORELLANA','CONDUCTOR'),
(N'30043',N'CARLOS',N'RODRIGUEZ','CONDUCTOR'),
(N'30044',N'GERSON',N'RODRIGUEZ','CONDUCTOR'),
(N'40001',N'ARCENIO',N'CRIBAS DIAZ','CONDUCTOR'),
(N'40002',N'JUAN',N'MIGUEL CACERES','CONDUCTOR'),
(N'40003',N'JAIME',N'SOSA','CONDUCTOR'),
(N'40004',N'FREDY',N'ROLANDO CARPIO','CONDUCTOR');
INSERT INTO dbo.personas (id_empresa,documento,tipo_documento,nombres,apellidos,cargo,activo,eliminado,creado_por,fecha_creacion)
SELECT @IdEmpresa, p.documento, 'INTERNO', p.nombres, p.apellidos, p.cargo, 1, 0, 'seed-transgar', @Ahora
FROM #per p
WHERE NOT EXISTS (SELECT 1 FROM dbo.personas x WHERE x.id_empresa=@IdEmpresa AND x.documento=p.documento AND x.eliminado=0);
PRINT 'Personas insertadas: '+CAST(@@ROWCOUNT AS varchar(10));
DROP TABLE #per;
PRINT '=== 30 completado ===';
