-- =============================================================================
-- SCRIPT: Creación de tabla monedas y carga de datos
-- Proyecto: eGestion360
-- Fecha: 2026-04-23
-- Descripción: Tabla de monedas ISO 4217 para el mantenimiento de empresas
-- =============================================================================

-- Creación de tabla
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'monedas')
BEGIN
    CREATE TABLE monedas (
        codigo_iso  NVARCHAR(3)   NOT NULL,
        nombre      NVARCHAR(100) NOT NULL,
        simbolo     NVARCHAR(10)  NOT NULL,
        activo      BIT           NOT NULL CONSTRAINT DF_monedas_activo DEFAULT 1,
        CONSTRAINT PK_monedas PRIMARY KEY (codigo_iso)
    );
    PRINT 'Tabla monedas creada.';
END
ELSE
    PRINT 'La tabla monedas ya existe.';
GO

-- Carga de datos (solo si está vacía)
IF NOT EXISTS (SELECT 1 FROM monedas)
BEGIN
    INSERT INTO monedas (codigo_iso, nombre, simbolo, activo) VALUES
    ('AED', 'Dírham de los EAU',                   'AED',  1),
    ('AFN', 'Afgani afgano',                         'AFN',  1),
    ('ALL', 'Lek albanés',                           'L',    1),
    ('AMD', 'Dram armenio',                          'AMD',  1),
    ('ANG', 'Florín antillano neerlandés',           'ƒ',    1),
    ('AOA', 'Kwanza angoleño',                       'Kz',   1),
    ('ARS', 'Peso argentino',                        '$',    1),
    ('AUD', 'Dólar australiano',                     'A$',   1),
    ('AWG', 'Florín arubeño',                        'ƒ',    1),
    ('AZN', 'Manat azerbaiyano',                     '₼',    1),
    ('BAM', 'Marco bosnio convertible',              'KM',   1),
    ('BBD', 'Dólar de Barbados',                     'Bds$', 1),
    ('BDT', 'Taka bangladesí',                       '৳',    1),
    ('BGN', 'Lev búlgaro',                           'лв',   1),
    ('BHD', 'Dinar bareiní',                         'BD',   1),
    ('BIF', 'Franco burundés',                       'Fr',   1),
    ('BMD', 'Dólar de Bermudas',                     '$',    1),
    ('BND', 'Dólar de Brunéi',                       'B$',   1),
    ('BOB', 'Boliviano',                             'Bs',   1),
    ('BRL', 'Real brasileño',                        'R$',   1),
    ('BSD', 'Dólar bahameño',                        'B$',   1),
    ('BTN', 'Ngultrum butanés',                      'Nu',   1),
    ('BWP', 'Pula botsuanesa',                       'P',    1),
    ('BYN', 'Rublo bielorruso',                      'Br',   1),
    ('BZD', 'Dólar de Belice',                       'BZ$',  1),
    ('CAD', 'Dólar canadiense',                      'CA$',  1),
    ('CDF', 'Franco congoleño',                      'Fr',   1),
    ('CHF', 'Franco suizo',                          'Fr',   1),
    ('CLP', 'Peso chileno',                          '$',    1),
    ('CNY', 'Yuan chino',                            '¥',    1),
    ('COP', 'Peso colombiano',                       '$',    1),
    ('CRC', 'Colón costarricense',                   '₡',    1),
    ('CUP', 'Peso cubano',                           '$',    1),
    ('CVE', 'Escudo caboverdiano',                   '$',    1),
    ('CZK', 'Corona checa',                          'Kč',   1),
    ('DJF', 'Franco yibutiano',                      'Fr',   1),
    ('DKK', 'Corona danesa',                         'kr',   1),
    ('DOP', 'Peso dominicano',                       'RD$',  1),
    ('DZD', 'Dinar argelino',                        'دج',   1),
    ('EGP', 'Libra egipcia',                         'E£',   1),
    ('ERN', 'Nakfa eritreo',                         'Nfk',  1),
    ('ETB', 'Birr etíope',                           'Br',   1),
    ('EUR', 'Euro',                                  '€',    1),
    ('FJD', 'Dólar fiyiano',                         'FJ$',  1),
    ('FKP', 'Libra malvinense',                      '£',    1),
    ('GBP', 'Libra esterlina',                       '£',    1),
    ('GEL', 'Lari georgiano',                        '₾',    1),
    ('GHS', 'Cedi ghanés',                           '₵',    1),
    ('GIP', 'Libra gibraltareña',                    '£',    1),
    ('GMD', 'Dalasi gambiano',                       'D',    1),
    ('GNF', 'Franco guineano',                       'Fr',   1),
    ('GTQ', 'Quetzal guatemalteco',                  'Q',    1),
    ('GYD', 'Dólar de Guyana',                       'GY$',  1),
    ('HKD', 'Dólar de Hong Kong',                    'HK$',  1),
    ('HNL', 'Lempira hondureño',                     'L',    1),
    ('HTG', 'Gourde haitiano',                       'G',    1),
    ('HUF', 'Forinto húngaro',                       'Ft',   1),
    ('IDR', 'Rupia indonesia',                       'Rp',   1),
    ('ILS', 'Nuevo séquel israelí',                  '₪',    1),
    ('INR', 'Rupia india',                           '₹',    1),
    ('IQD', 'Dinar iraquí',                          'IQD',  1),
    ('IRR', 'Rial iraní',                            'IRR',  1),
    ('ISK', 'Corona islandesa',                      'kr',   1),
    ('JMD', 'Dólar jamaicano',                       'J$',   1),
    ('JOD', 'Dinar jordano',                         'JD',   1),
    ('JPY', 'Yen japonés',                           '¥',    1),
    ('KES', 'Chelín keniata',                        'KSh',  1),
    ('KGS', 'Som kirguís',                           'с',    1),
    ('KHR', 'Riel camboyano',                        '៛',    1),
    ('KMF', 'Franco comorense',                      'Fr',   1),
    ('KPW', 'Won norcoreano',                        '₩',    1),
    ('KRW', 'Won surcoreano',                        '₩',    1),
    ('KWD', 'Dinar kuwaití',                         'KD',   1),
    ('KZT', 'Tenge kazajo',                          '₸',    1),
    ('LAK', 'Kip laosiano',                          '₭',    1),
    ('LBP', 'Libra libanesa',                        'L£',   1),
    ('LKR', 'Rupia de Sri Lanka',                    'Rs',   1),
    ('LRD', 'Dólar liberiano',                       'L$',   1),
    ('LSL', 'Loti lesotense',                        'L',    1),
    ('LYD', 'Dinar libio',                           'LD',   1),
    ('MAD', 'Dírham marroquí',                       'MAD',  1),
    ('MDL', 'Leu moldavo',                           'L',    1),
    ('MGA', 'Ariary malgache',                       'Ar',   1),
    ('MKD', 'Denar macedonio',                       'ден',  1),
    ('MMK', 'Kyat birmano',                          'K',    1),
    ('MNT', 'Tugrik mongol',                         '₮',    1),
    ('MOP', 'Pataca macaense',                       'P',    1),
    ('MRU', 'Uguiya mauritana',                      'UM',   1),
    ('MUR', 'Rupia mauriciana',                      'Rs',   1),
    ('MVR', 'Rufiyaa maldiva',                       'Rf',   1),
    ('MWK', 'Kwacha malauí',                         'MK',   1),
    ('MXN', 'Peso mexicano',                         '$',    1),
    ('MYR', 'Ringgit malayo',                        'RM',   1),
    ('MZN', 'Metical mozambiqueño',                  'MT',   1),
    ('NAD', 'Dólar namibio',                         'N$',   1),
    ('NGN', 'Naira nigeriana',                       '₦',    1),
    ('NIO', 'Córdoba nicaragüense',                  'C$',   1),
    ('NOK', 'Corona noruega',                        'kr',   1),
    ('NPR', 'Rupia nepalesa',                        'Rs',   1),
    ('NZD', 'Dólar neozelandés',                     'NZ$',  1),
    ('OMR', 'Rial omaní',                            'OMR',  1),
    ('PAB', 'Balboa panameño',                       'B/.',  1),
    ('PEN', 'Sol peruano',                           'S/',   1),
    ('PGK', 'Kina de Papúa Nueva Guinea',            'K',    1),
    ('PHP', 'Peso filipino',                         '₱',    1),
    ('PKR', 'Rupia pakistaní',                       'Rs',   1),
    ('PLN', 'Esloti polaco',                         'zł',   1),
    ('PYG', 'Guaraní paraguayo',                     '₲',    1),
    ('QAR', 'Riyal catarí',                          'QR',   1),
    ('RON', 'Leu rumano',                            'lei',  1),
    ('RSD', 'Dinar serbio',                          'din',  1),
    ('RUB', 'Rublo ruso',                            '₽',    1),
    ('RWF', 'Franco ruandés',                        'Fr',   1),
    ('SAR', 'Riyal saudí',                           'SR',   1),
    ('SBD', 'Dólar de las Islas Salomón',            'SI$',  1),
    ('SCR', 'Rupia de Seychelles',                   'Rs',   1),
    ('SDG', 'Libra sudanesa',                        '£',    1),
    ('SEK', 'Corona sueca',                          'kr',   1),
    ('SGD', 'Dólar de Singapur',                     'S$',   1),
    ('SHP', 'Libra de Santa Elena',                  '£',    1),
    ('SLE', 'Leone de Sierra Leona',                 'Le',   1),
    ('SOS', 'Chelín somalí',                         'Sh',   1),
    ('SRD', 'Dólar surinamés',                       '$',    1),
    ('STN', 'Dobra de Santo Tomé',                   'Db',   1),
    ('SVC', 'Colón salvadoreño',                     '₡',    1),
    ('SYP', 'Libra siria',                           '£',    1),
    ('SZL', 'Lilangeni suazi',                       'L',    1),
    ('THB', 'Baht tailandés',                        '฿',    1),
    ('TJS', 'Somoni tayiko',                         'SM',   1),
    ('TMT', 'Manat turcomano',                       'T',    1),
    ('TND', 'Dinar tunecino',                        'DT',   1),
    ('TOP', 'Pa''anga tongano',                      'T$',   1),
    ('TRY', 'Lira turca',                            '₺',    1),
    ('TTD', 'Dólar de Trinidad y Tobago',            'TT$',  1),
    ('TWD', 'Nuevo dólar taiwanés',                  'NT$',  1),
    ('TZS', 'Chelín tanzano',                        'Sh',   1),
    ('UAH', 'Grivna ucraniana',                      '₴',    1),
    ('UGX', 'Chelín ugandés',                        'Sh',   1),
    ('USD', 'Dólar estadounidense',                  '$',    1),
    ('UYU', 'Peso uruguayo',                         '$U',   1),
    ('UZS', 'Som uzbeko',                            'лв',   1),
    ('VES', 'Bolívar venezolano',                    'Bs',   1),
    ('VND', 'Dong vietnamita',                       '₫',    1),
    ('VUV', 'Vatu de Vanuatu',                       'Vt',   1),
    ('WST', 'Tālā samoano',                          'T',    1),
    ('XAF', 'Franco CFA de África Central',          'Fr',   1),
    ('XCD', 'Dólar del Caribe Oriental',             'EC$',  1),
    ('XOF', 'Franco CFA de África Occidental',       'Fr',   1),
    ('XPF', 'Franco CFP',                            'Fr',   1),
    ('YER', 'Rial yemení',                           'YER',  1),
    ('ZAR', 'Rand sudafricano',                      'R',    1),
    ('ZMW', 'Kwacha zambiano',                       'ZK',   1),
    ('ZWL', 'Dólar zimbabuense',                     '$',    1);

    PRINT 'Datos insertados: ' + CAST(@@ROWCOUNT AS NVARCHAR(10));
END
ELSE
    PRINT 'La tabla monedas ya contiene datos. No se insertaron registros.';
GO
